### PR TITLE
Restructured pyiron.md, using a stepwise deployment procedure.

### PR DESCRIPTION
**Pull request by pbeckm**
Gave pyiron.md a step-by-step structure much like the ontodocker page.

### CODE REVIEW

**Review by muh-hassani — APPROVED** [review]
I like the numbering of the steps and the changes. It will be easier to follow. Thanks, @pbeckm .

**Review by schaarj — CHANGES_REQUESTED** [review]
I briefly looked at it, however at least the section 
> all You need is ......  

should be completed, I will fill this with a more thorough review tomorrow

**Review by schaarj — APPROVED** [review]

**Comment by schaarj** [comment]
I made some changes @pbeckm and @muh-hassani if you are fine with these, this can be merged

**Comment by pbeckm** [comment]
I'm not in the reviewer's list, but if You ask me, looks splendid.

**Comment by muh-hassani** [comment]
@schaarj @pbeckm thanks for the improvements to the guide. I made some more aesthetic changes. It is ready to be merged from my side.

**Comment by pbeckm** [comment]
Yes, looks fine, please merge.

**Pull request merged**
